services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    devlop:
      watch:
      - action:sync
        path:./src
        target:/app/src
          - node_modules/
      - action: rebuild
        path: package.json 